# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notebook.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import notebookClasses


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 90, 77, 199))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.buttonPrint = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonPrint.setObjectName("buttonPrint")
        self.verticalLayout.addWidget(self.buttonPrint)

        self.buttonAppend = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonAppend.setObjectName("buttonAppend")
        self.verticalLayout.addWidget(self.buttonAppend)

        self.buttonEdit = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonEdit.setObjectName("buttonEdit")
        self.verticalLayout.addWidget(self.buttonEdit)

        self.buttonDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonDelete.setObjectName("buttonDelete")
        self.verticalLayout.addWidget(self.buttonDelete)

        self.buttonSave = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 90, 361, 341))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setPlaceholderText("notebook Content")

        self.currentBook = QtWidgets.QLabel(self.centralwidget)
        self.currentBook.setGeometry(QtCore.QRect(160, 30, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)

        self.currentBook.setFont(font)
        self.currentBook.setObjectName("currentBook")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewnotebook = QtWidgets.QAction(MainWindow)
        self.actionNewnotebook.setObjectName("actionNewnotebook")
        self.actionOpennotebook = QtWidgets.QAction(MainWindow)
        self.actionOpennotebook.setObjectName("actionOpennotebook")
        self.actionSavenotebook = QtWidgets.QAction(MainWindow)
        self.actionSavenotebook.setObjectName("actionSavenotebook")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNewnotebook)
        self.menuFile.addAction(self.actionOpennotebook)
        self.menuFile.addAction(self.actionSavenotebook)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPrint.setToolTip(_translate("MainWindow", "Prints content of notebook."))
        self.buttonPrint.setText(_translate("MainWindow", "Print Content"))
        self.buttonAppend.setToolTip(_translate("MainWindow", "Appends note to notebook."))
        self.buttonAppend.setText(_translate("MainWindow", "Add note"))
        self.buttonEdit.setToolTip(_translate("MainWindow", "Edits existing note."))
        self.buttonEdit.setText(_translate("MainWindow", "Edit note"))
        self.buttonDelete.setToolTip(_translate("MainWindow", "Deletes a note."))
        self.buttonDelete.setText(_translate("MainWindow", "Delete note"))
        self.buttonSave.setToolTip(_translate("MainWindow", "Saves notes into notebook."))
        self.buttonSave.setText(_translate("MainWindow", "Save notes"))
        self.currentBook.setText(_translate("MainWindow", "Untitled"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNewnotebook.setText(_translate("MainWindow", "New notebook"))
        self.actionNewnotebook.setToolTip(_translate("MainWindow", "Creates new notebook"))
        self.actionNewnotebook.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpennotebook.setText(_translate("MainWindow", "Open notebook"))
        self.actionOpennotebook.setToolTip(_translate("MainWindow", "Opens another notebook"))
        self.actionOpennotebook.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSavenotebook.setText(_translate("MainWindow", "Save notebook"))
        self.actionSavenotebook.setToolTip(_translate("MainWindow", "Saves notes to notebook"))
        self.actionSavenotebook.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quits program"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

    def printContent(self):
        pass
    def createLine(self):
        pass
    def replaceLine(self):
        pass
    def deleteLine(self):
        pass
    def changeBook(self):
        pass
    def saveContent(self):
        pass
    def Exit(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
